name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: setup env
      shell: bash
      run: |
        echo "::set-env name=GOPATH::${{ github.workspace }}/go"
        echo "::add-path::${{ github.workspace }}/go/bin"
        
    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        path: go/src/github.com/${{ github.repository }}

    - name: Get dependencies
      env:
        GO111MODULE: off
      run: |
        cd $GOPATH/src/github.com/${{ github.repository }}
        go get -v github.com/therecipe/qt/cmd/...
        go get -v github.com/gorilla/websocket
        docker pull therecipe/qt:windows_64_static

    - name: Build
      run: |
        cd $GOPATH/src/github.com/${{ github.repository }}
        $(go env GOPATH)/bin/qtdeploy -docker build windows_64_static
